repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        args: ["--profile", "black"]
        types: [python]
        exclude: ^(requirements)/

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        args: ["--line-length", "100"]
        types: [python]
        exclude: ^(requirements)/

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        args: ["--max-line-length", "100", "--ignore=E203,W503,N815,N806"]
        additional_dependencies:
          - pep8-naming
          - flake8-absolute-import
          - flake8-comprehensions
          - flake8-bugbear
        types: [python]
        exclude: ^(requirements)/

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        args:
          - --py311-plus
          - --keep-runtime-typing
        types: [python]
        exclude: ^(requirements)/

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks
